### ISSUE TITLE
Url /site/modules/MarkupProcesswirePhotoswipe/.* not found

### ISSUE THREAD

**Issue by hberg539** [blynx/MarkupProcesswirePhotoswipe#2]
After installing the module, i added the following snipped as stated in the readme to my template:
`$pwpswp = $modules->get('MarkupProcesswirePhotoswipe');
 echo $pwpswp->renderGallery($page->get("images"));`

After that, the following scripts are added at the end of the page:
`<script src="/site/modules/MarkupProcesswirePhotoswipe/photoswipe/photoswipe.min.js"></script>
<script src="/site/modules/MarkupProcesswirePhotoswipe/photoswipe/photoswipe-ui-default.min.js"></script>
<script src="/site/modules/MarkupProcesswirePhotoswipe/pwpswp.js"></script>`

The issue is, there is no MarkupProcesswirePhotoswipe folder, only a MarkupPwpswpGallery folder.
Seems like some naming issue, i suppose?
Thanks!

**Comment by blynx** [comment]
Hm!

Weird, I just tested a fresh installation from the modules directory via `modules > New > Add Module From Directory` and it worked fine for me.

How did you install the module and was it a fresh installation or an update?  
Could you provide some more information, like Processwire version and/or any actual error messages from the browser console or from PHP?

Even better: If you have TracyDebugger (http://modules.processwire.com/modules/tracy-debugger/) installed, could you paste any error messages it gives here?

Thanks!

**Comment by hberg539** [comment]
I have found the issue!

When installing with "Add module From Url" with the url "https://github.com/blynx/MarkupProcesswirePhotoswipe/archive/master.zip", it puts the module into the folder:
/site/modules/MarkupPwpswpGallery/

Then all links to javascript and css files were going nowhere.

When putting the master.zip directly to the /site/modules/ folder, extracting it and renaming it to "MarkupProcesswirePhotoswipe", like stated in the instructions, it works!

Seems like ProcessWire is extracting the foldername from one of the image placement modules, i suppose. I'm using ProcessWire in the Version 3.0.62 (fresh install with default template).

By the way, the Petersburger Hängung is really awesome, really like it!

Thanks.

**Comment by blynx** [comment]
Ah, thanks!
Could have tried that, too -.-  ... I will see if I can work it out in my module or if this could be solved in processwire.

Glad you like it! :)

**Comment by blynx** [comment]
Okay, fixed it. a656e5716671c29ff60657e1d650839b0987821b

The module will determine the correct url from the actual file path now. So it doesn't matter in which folder the modules are.
